# Generated by Django 6.0.2 on 2026-02-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
