# Generated by Django 6.0.2 on 2026-02-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_vendor_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='description',
        ),
    ]
