# Generated by Django 6.0.2 on 2026-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='quantity',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
