# Generated by Django 4.2.29 on 2026-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(choices=[('Liters', 'Liters'), ('KGs', 'KGs'), ('Units', 'Units')], default='Units', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
