# Generated by Django 4.2.29 on 2026-04-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0019_alter_animal_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_sent', models.DateField()),
                ('date_received', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adal_records', to='animals.animal')),
            ],
        ),
    ]
