# Generated by Django 6.0.2 on 2026-02-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('species', models.CharField(choices=[('Bovine', 'Bovine'), ('Equine', 'Equine'), ('Porcine', 'Porcine')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_status', models.CharField(default='Healthy', max_length=100)),
                ('last_vaccination', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
