# Generated by Django 6.0.2 on 2026-02-20 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='weight_kg',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='last_vaccination',
        ),
        migrations.AddField(
            model_name='animal',
            name='last_vet_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('ill', 'Ill/In Treatment'), ('quarantine', 'Quarantine')], default='healthy', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Chicken', 'Chicken')], max_length=50),
        ),
    ]
