# Generated by Django 6.0.2 on 2026-02-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_weight_kg_animal_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dam',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_from_dam', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sire',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_from_sire', to='animals.animal'),
        ),
    ]
