# Generated by Django 6.0.2 on 2026-02-20 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_dam_animal_sire'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('administered_by', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
                ('vaccine_resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.resource')),
            ],
        ),
    ]
