# Generated by Django 6.0.2 on 2026-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_vaccinationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Cow', 'Cow'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Chicken', 'Chicken')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
