# Generated by Django 6.0.2 on 2026-02-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animalpurpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animalpurpose'),
        ),
    ]
