# Generated by Django 6.0.2 on 2026-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='notes',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
