# Generated by Django 6.0.2 on 2026-02-22 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animal_notes'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine_resource',
            field=models.ForeignKey(limit_choices_to={'resource_type__name': 'Vaccine'}, on_delete=django.db.models.deletion.PROTECT, to='resources.resource'),
        ),
    ]
