# Generated by Django 6.0.2 on 2026-02-23 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_vaccinationrecord_vaccine_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='administered_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkup', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('checked_by', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='animals.animal')),
            ],
        ),
    ]
