# Generated by Django 6.0.2 on 2026-02-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_alter_vaccinationrecord_administered_by_healthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='animals.animal'),
        ),
    ]
