# Generated by Django 6.0.2 on 2026-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_alter_healthrecord_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals'),
        ),
    ]
