# Generated by Django 6.0.2 on 2026-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
