# Generated by Django 4.2.29 on 2026-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_alter_animal_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
