# Generated by Django 4.2.29 on 2026-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_alter_animal_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
    ]
