# Generated by Django 4.2.29 on 2026-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_alter_animal_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('next_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vaccine_resource',
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('died', 'Died'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='HealthRecord',
        ),
        migrations.DeleteModel(
            name='VaccinationRecord',
        ),
        migrations.AddField(
            model_name='animalhistory',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='animals.animal'),
        ),
    ]
