# Generated by Django 4.2.29 on 2026-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_animal_created_at_animal_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
