# Generated by Django 4.2.29 on 2026-03-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_rolepermissionmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='users.RolePermissionMapping', to='users.permission'),
        ),
        migrations.AlterField(
            model_name='rolepermissionmapping',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_mappings', to='users.permission'),
        ),
        migrations.AlterField(
            model_name='rolepermissionmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='users.role'),
        ),
    ]
