# Generated by Django 4.2.29 on 2026-03-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_inventorytransaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('content_type', 'category_name', 'item_name')},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='object_id',
        ),
    ]
