# Generated by Django 4.2.29 on 2026-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('content_type', 'category_name', 'item_name', 'object_id')},
        ),
    ]
