# Generated by Django 4.2.29 on 2026-03-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_unique_together_inventory_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit',
            field=models.CharField(choices=[('Liters', 'Liters'), ('KGs', 'KGs'), ('Units', 'Units')], default='Units', max_length=50),
        ),
    ]
