# Generated by Django 4.2.29 on 2026-03-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_sale_price_per_item_financialtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='category_name',
            field=models.CharField(default='Milk (Cow)', help_text='e.g., Poultry Sales', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
