# Generated by Django 4.2.29 on 2026-03-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_sale_category_name_sale_description_sale_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='item_name',
            field=models.CharField(default='Morning batch', max_length=100),
            preserve_default=False,
        ),
    ]
