# Generated by Django 4.2.29 on 2026-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_financialtransaction_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
