# Generated by Django 4.2.29 on 2026-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
